version: '3.1'
services:
  database:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Strong(!)Password1
  server:
    build: server/Server
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: http://*:5000
      DBHOST: database
      DBPORT: 1433
      DBUSER: sa
      DBPASS: Strong(!)Password1
      DBDATABASE: master
    depends_on:
      - database
  client:
      build: client
      ports:
          - "80:80"
      volumes:
          - ./client/nginx.conf:/etc/nginx/nginx.conf
